import subprocess
from pathlib import Path
import model.iaxray as ia
import os
print("TEST CREATED AND TESTED BY ARNAU ALBERT SANCHEZ")
print("INFO: in this file we are going to test all the scripts excecuting")
print("them with the python library subprocess and storing the results in")
print("the folder with the path: test_results/ also the IA that doesn't return")
print("a file, it returns a message with the results ")
print('----------------------------------------------------------------------')
# subprocess.run(['./random',"5"])
# file_up = Path('dna.fasta')
# new_filename = Path('test_results/test_random_seq.fasta')
# file_up.rename(new_filename)
# print("it returns the file test_random_seq.fasta with 5 bases of DNA")
# print('----------------------------------------------------------------------')
# subprocess.run(['./random',"asd"])
# print("it doesn't return anything as it should because the input is not a number")
# print('----------------------------------------------------------------------')
# subprocess.run(['./extract_cds',"app.py"])
# file_up = Path('resultado.fasta')
# new_filename = Path('test_results/test_resultadofail.txt')
# file_up.rename(new_filename)
# print('It returns the file resultado.fasta empty')
# print('----------------------------------------------------------------------')
# print(subprocess.run(['./extract_cds',"cdsext/sequence.gb"]))
# file_up = Path('resultado.fasta')
# new_filename = Path('test_results/test_resultadogood.txt')
# file_up.rename(new_filename)
# print('It returns the file resultadogood.txt with his respective CDS sequences')
# print('----------------------------------------------------------------------')
# subprocess.run(["./dna_rna","test_results/test_random_seq.fasta"])
# print("it returns the file test_random_seq_modified.fasta with the translations of the DNA sequence to RNA")
# print('----------------------------------------------------------------------')
# subprocess.run(["./dna_protein","test_results/test_random_seq.fasta"])
# print("it returns the file test_random_seq_modified.fasta with the translations of the DNA sequence to PROTEIN")
# subprocess.run(["./genbankToFastaV3","cdsext/sequence.gb"])
# file_up = Path('gb_to_fasta.fasta')
# new_filename = Path('test_results/test_genbank_to_fasta_NC_045512.fasta')
# file_up.rename(new_filename)
# print("It returns a fine with the name of the accession number of the genbang with the corresponding sequence writed in")
# print('----------------------------------------------------------------------')
# print("FOR THIS TEST WE ARE GOING TO USE 2 TOOLS, ONE TESTED BEFORE (RANDOM SEQUENCE)\n TO CREATE THE 2 FASTAS WE ARE GOING TO USE AND THE ONE THAT WE ARE TESTING NOW")
# subprocess.run(["./random","15"])
# file_up = Path('dna.fasta')
# new_filename = Path('test_results/local1test.fasta')
# file_up.rename(new_filename)
# subprocess.run(["./random","35"])
# file_up = Path('dna.fasta')
# new_filename = Path('test_results/local2test.fasta')
# file_up.rename(new_filename)
# subprocess.run(["./local_alignment","test_results/local1test.fasta","test_results/local2test.fasta"])
# file_up = Path('alignment_result.txt')
# new_filename = Path('test_results/test_alignment_result.txt')
# file_up.rename(new_filename)
# print("It returns the file test_alignment_result.txt with the score of the alignment and the bases that match")
# print('----------------------------------------------------------------------')
# print("NOW WE ARE GOING TO TEST THE IA MODEL GIVING THEM 2 PICTURES OF LUNGS \n ONE WITH PNEUMONIA AND ONE NORMAL")
# print(ia.IAML.ask("test_pictures_ia/NORMAL2-IM-1427-0001.jpeg"))
# print("It returns that the result is normal as it should because the picture is normal")
# print(ia.IAML.ask("test_pictures_ia/person1946_bacteria_4874.jpeg"))
# print("It returns that the result is pneumonia as it should because the picture is pneumonia")



for pic in os.walk("test_pictures_ia"):
    for file in pic[2]:
        print(file)
        print(ia.IAML.ask(f"test_pictures_ia/{file}"))

